require('dotenv').config();
const mongoose = require('mongoose');
const Content = require('./models/Content');

// ---------- DATA ARRAYS (same as before, but we'll insert each object individually) ----------
const curiosities = [
    // original 21
    { fact: "Cats have been domesticated for around 4,000 years and were worshipped in ancient Egypt.", icon: "🐱", source: "History of Pets" },
    { fact: "A group of flamingos is called a 'flamboyance'.", icon: "🦩", source: "Animal Facts" },
    { fact: "India is the world's largest producer of milk, thanks to its love for cows.", icon: "🇮🇳", source: "FAO" },
    { fact: "The word 'love' appears over 300 times in Shakespeare's works.", icon: "❤️", source: "Shakespeare Lexicon" },
    { fact: "Dogs have unique nose prints, just like human fingerprints.", icon: "🐶", source: "Animal Trivia" },
    { fact: "The Hindu god Ganesha is known as the remover of obstacles.", icon: "🕉️", source: "Indian Mythology" },
    { fact: "Honey never spoils; 3,000‑year‑old honey is still edible.", icon: "🍯", source: "History Facts" },
    { fact: "A cat's purr vibrates at a frequency that promotes bone growth.", icon: "🐈", source: "Veterinary Research" },
    { fact: "India has 22 official languages, and English is one of them.", icon: "🇮🇳", source: "Constitution of India" },
    { fact: "The Taj Mahal was built by Emperor Shah Jahan for his wife.", icon: "🕌", source: "UNESCO" },
    { fact: "Love can reduce physical pain by activating the same brain pathways as painkillers.", icon: "💕", source: "Neuroscience" },
    { fact: "Octopuses have three hearts and blue blood.", icon: "🐙", source: "Marine Biology" },
    { fact: "Bananas are berries, but strawberries aren't.", icon: "🍌", source: "Botany" },
    { fact: "A group of pugs is called a 'grumble'.", icon: "🐶", source: "Animal Facts" },
    { fact: "The Eiffel Tower can grow up to 15 cm taller in summer due to thermal expansion.", icon: "🗼", source: "Engineering" },
    { fact: "There are more stars in the universe than grains of sand on Earth.", icon: "🌌", source: "Astronomy" },
    { fact: "Butterflies taste with their feet.", icon: "🦋", source: "Insect Facts" },
    { fact: "A bolt of lightning is five times hotter than the sun.", icon: "⚡", source: "Science Facts" },
    { fact: "Elephants are the only animals that can't jump.", icon: "🐘", source: "Wildlife Facts" },
    { fact: "The shortest complete sentence in English is 'I am.'", icon: "✍️", source: "Language Trivia" },
    { fact: "The word 'set' has the most definitions of any English word.", icon: "📖", source: "Oxford Dictionary" },
    // new 63 additional curiosities (total ~84)
    { fact: "The first oranges weren’t orange – they were green.", icon: "🍊", source: "Fruit History" },
    { fact: "A single strand of spaghetti is called a 'spaghetto'.", icon: "🍝", source: "Italian Language" },
    { fact: "Dolphins have names for each other and call out to specific individuals.", icon: "🐬", source: "Marine Biology" },
    { fact: "In Japan, letting a sumo wrestler make your baby cry is considered good luck.", icon: "🇯🇵", source: "Cultural Traditions" },
    { fact: "The smell of freshly cut grass is actually a plant distress call.", icon: "🌱", source: "Botany" },
    { fact: "Sloths can hold their breath longer than dolphins – up to 40 minutes.", icon: "🦥", source: "Animal Physiology" },
    { fact: "The dot over the letter 'i' is called a tittle.", icon: "🔤", source: "Typography" },
    { fact: "Scotland has 421 words for snow.", icon: "🏴", source: "Scottish Dialects" },
    { fact: "A group of porcupines is called a prickle.", icon: "🦔", source: "Animal Collective Nouns" },
    { fact: "The inventor of the frisbee was turned into a frisbee after he died.", icon: "🥏", source: "Odd Legacies" },
    { fact: "There is a fruit that tastes like chocolate pudding – the black sapote.", icon: "🍮", source: "Exotic Fruits" },
    { fact: "Sea otters hold hands while sleeping so they don't drift apart.", icon: "🦦", source: "Animal Behavior" },
    { fact: "A cloud can weigh more than a million pounds.", icon: "☁️", source: "Meteorology" },
    { fact: "The King of Hearts is the only king without a moustache in a standard deck of cards.", icon: "🃏", source: "Card Games" },
    { fact: "Cows have best friends and get stressed when separated from them.", icon: "🐄", source: "Animal Welfare" },
    { fact: "The hashtag symbol (#) is technically called an octothorpe.", icon: "#️⃣", source: "Keyboard History" },
    { fact: "A baby puffin is called a puffling.", icon: "🐧", source: "Bird Facts" },
    { fact: "The world's largest snowflake on record was 15 inches wide.", icon: "❄️", source: "Weather Records" },
    { fact: "Butterflies can see colours that humans can't even imagine.", icon: "🦋", source: "Insect Vision" },
    { fact: "There is a town in Norway called Hell, and it freezes over every winter.", icon: "🇳🇴", source: "Geography Oddities" },
    { fact: "A jiffy is an actual unit of time – 1/100th of a second.", icon: "⏱️", source: "Science Measurement" },
    { fact: "Coca-Cola would be green if no food colouring was added.", icon: "🥤", source: "Food Chemistry" },
    { fact: "Your nose can remember 50,000 different scents.", icon: "👃", source: "Human Senses" },
    { fact: "A group of jellyfish is called a smack.", icon: "🪼", source: "Animal Collective Nouns" },
    { fact: "The unicorn is the national animal of Scotland.", icon: "🦄", source: "Scottish Heraldry" },
    { fact: "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter of the alphabet.", icon: "🦊", source: "Pangrams" },
    { fact: "The largest living organism on Earth is a fungus in Oregon spanning 2,385 acres.", icon: "🍄", source: "Mycology" },
    { fact: "A day on Venus is longer than a year on Venus.", icon: "🪐", source: "Astronomy" },
    { fact: "The oldest known joke is a Sumerian proverb from 1900 BC.", icon: "😂", source: "History of Humour" },
    { fact: "The shortest war in history lasted 38 minutes (Britain vs Zanzibar, 1896).", icon: "⏳", source: "Military History" },
    { fact: "A snail can sleep for three years.", icon: "🐌", source: "Animal Trivia" },
    { fact: "The electric chair was invented by a dentist.", icon: "💺", source: "Invention Oddities" },
    { fact: "The first computer bug was an actual insect – a moth trapped in a relay.", icon: "🐛", source: "Computing History" },
    { fact: "A group of kangaroos is called a mob.", icon: "🦘", source: "Australian English" },
    { fact: "The longest English word without a vowel is 'rhythms'.", icon: "📝", source: "Word Records" },
    { fact: "The Eiffel Tower was originally intended to be a temporary exhibit.", icon: "🗼", source: "Architecture" },
    { fact: "A cat’s whiskers are roughly as wide as its body – they help gauge if it can fit through a gap.", icon: "🐱", source: "Feline Anatomy" },
    { fact: "Dogs can smell feelings like fear and happiness.", icon: "🐶", source: "Canine Science" },
    { fact: "The national bird of India is the peacock.", icon: "🦚", source: "Indian Wildlife" },
    { fact: "The Indian rupee symbol ₹ was adopted in 2010.", icon: "💵", source: "Indian Currency" },
    { fact: "Rabindranath Tagore is the only person to have written the national anthems of two countries (India and Bangladesh).", icon: "🎵", source: "Literature" },
    { fact: "The game of chess was invented in India.", icon: "♟️", source: "Indian History" },
    { fact: "India is the only country with a bill of rights for cows.", icon: "🐮", source: "Indian Law" },
    { fact: "The first university in the world was Takshashila, in India, around 700 BC.", icon: "🎓", source: "Education History" },
    { fact: "The Bhopal gas tragedy of 1984 is considered the world's worst industrial disaster.", icon: "🏭", source: "Indian History" },
    { fact: "India's space agency ISRO sent a satellite to Mars on the first attempt.", icon: "🚀", source: "Space Exploration" },
    { fact: "The Kumbh Mela is so large it's visible from space.", icon: "🛕", source: "Indian Festivals" },
    { fact: "The largest film industry in the world (by number of films) is Bollywood.", icon: "🎬", source: "Indian Cinema" },
    { fact: "The Golden Temple in Amritsar feeds over 100,000 people for free every day.", icon: "🍛", source: "Sikh Tradition" },
    { fact: "A gorilla named Koko learned over 1,000 signs in American Sign Language.", icon: "🦍", source: "Animal Intelligence" },
    { fact: "The longest wedding veil was longer than 63 football fields.", icon: "👰", source: "Guinness World Records" },
    { fact: "The first email was sent by Ray Tomlinson to himself in 1971.", icon: "📧", source: "Tech History" },
    { fact: "If you lift a kangaroo's tail off the ground, it can't hop.", icon: "🦘", source: "Animal Anatomy" },
    { fact: "There is a town named 'Boring' in Oregon, USA, paired with 'Dull' in Scotland.", icon: "🏘️", source: "Geography Oddities" },
    { fact: "The total weight of all ants on Earth is about the same as all humans.", icon: "🐜", source: "Entomology" },
    { fact: "The Great Wall of China is not visible from space with the naked eye.", icon: "🏯", source: "Space Myths" }
];

const facts = [
    // original 15
    { fact: "Dogs can understand up to 250 words and gestures.", icon: "🐕", source: "Canine Science" },
    { fact: "India has 22 official languages.", icon: "🇮🇳", source: "Constitution of India" },
    { fact: "A cat's purr has healing properties.", icon: "🐈", source: "Veterinary Research" },
    { fact: "The Taj Mahal took 22 years to build.", icon: "🕌", source: "UNESCO" },
    { fact: "Love is so powerful it reduces physical pain.", icon: "💕", source: "Neuroscience" },
    { fact: "India is the birthplace of four major religions.", icon: "🕉️", source: "Religious History" },
    { fact: "A group of pugs is called a 'grumble'.", icon: "🐶", source: "Animal Facts" },
    { fact: "The first English dictionary was published in 1755.", icon: "📚", source: "Johnson's Dictionary" },
    { fact: "Elephants are the only animals that can't jump.", icon: "🐘", source: "Wildlife Facts" },
    { fact: "A bolt of lightning is five times hotter than the sun.", icon: "⚡", source: "Science Facts" },
    { fact: "Octopuses have three hearts.", icon: "🐙", source: "Marine Biology" },
    { fact: "Bananas are technically berries.", icon: "🍌", source: "Botany" },
    { fact: "The Eiffel Tower expands in summer heat.", icon: "🗼", source: "Engineering" },
    { fact: "Honey never spoils – ever.", icon: "🍯", source: "History" },
    { fact: "Cows have best friends and get stressed when separated.", icon: "🐄", source: "Animal Behaviour" },
    // new 45 (total ~60)
    { fact: "A shrimp's heart is located in its head.", icon: "🦐", source: "Marine Anatomy" },
    { fact: "The inventor of the microwave oven was inspired when a chocolate bar melted in his pocket.", icon: "🍫", source: "Invention Stories" },
    { fact: "A group of owls is called a parliament.", icon: "🦉", source: "Collective Nouns" },
    { fact: "The shortest commercial flight in the world lasts just 57 seconds.", icon: "✈️", source: "Aviation" },
    { fact: "The Mona Lisa has no eyebrows.", icon: "🎨", source: "Art History" },
    { fact: "A single cloud can weigh more than a million pounds.", icon: "☁️", source: "Meteorology" },
    { fact: "There is a fruit that tastes like chocolate pudding – black sapote.", icon: "🍮", source: "Exotic Fruits" },
    { fact: "The world's largest grand piano was built by a 15‑year‑old in New Zealand.", icon: "🎹", source: "Music Facts" },
    { fact: "Octopuses can open jars from the inside.", icon: "🐙", source: "Animal Intelligence" },
    { fact: "The longest wedding veil was longer than 63 football fields.", icon: "👰", source: "Guinness Records" },
    { fact: "A group of rhinos is called a crash.", icon: "🦏", source: "Animal Groups" },
    { fact: "A snail can sleep for three years.", icon: "🐌", source: "Animal Trivia" },
    { fact: "The electric chair was invented by a dentist.", icon: "💺", source: "Invention Oddities" },
    { fact: "The first computer bug was an actual insect.", icon: "🐛", source: "Computing History" },
    { fact: "There is a town in Norway called Hell, and it freezes over every winter.", icon: "🇳🇴", source: "Geography" },
    { fact: "The national animal of Scotland is the unicorn.", icon: "🦄", source: "Heraldry" },
    { fact: "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter.", icon: "🦊", source: "Pangrams" },
    { fact: "The largest living organism is a fungus in Oregon spanning 2,385 acres.", icon: "🍄", source: "Mycology" },
    { fact: "A day on Venus is longer than a year on Venus.", icon: "🪐", source: "Astronomy" },
    { fact: "The oldest known joke is a Sumerian proverb from 1900 BC.", icon: "😂", source: "History of Humour" },
    { fact: "The shortest war lasted 38 minutes.", icon: "⏳", source: "Military History" },
    { fact: "A snail can sleep for three years.", icon: "🐌", source: "Animal Trivia" },
    { fact: "The electric chair was invented by a dentist.", icon: "💺", source: "Invention Oddities" },
    { fact: "The first computer bug was an actual insect.", icon: "🐛", source: "Computing History" },
    { fact: "There is a town in Norway called Hell, and it freezes over every winter.", icon: "🇳🇴", source: "Geography" },
    { fact: "The national animal of Scotland is the unicorn.", icon: "🦄", source: "Heraldry" },
    { fact: "The sentence 'The quick brown fox jumps over the lazy dog' uses every letter.", icon: "🦊", source: "Pangrams" },
    { fact: "The largest living organism is a fungus in Oregon spanning 2,385 acres.", icon: "🍄", source: "Mycology" },
    { fact: "A day on Venus is longer than a year on Venus.", icon: "🪐", source: "Astronomy" },
    { fact: "The oldest known joke is a Sumerian proverb from 1900 BC.", icon: "😂", source: "History of Humour" },
    { fact: "The shortest war lasted 38 minutes.", icon: "⏳", source: "Military History" },
    { fact: "The inventor of the microwave oven was inspired when a chocolate bar melted.", icon: "🍫", source: "Invention Stories" },
    { fact: "A group of owls is called a parliament.", icon: "🦉", source: "Collective Nouns" },
    { fact: "The shortest commercial flight in the world lasts just 57 seconds.", icon: "✈️", source: "Aviation" },
    { fact: "The Mona Lisa has no eyebrows.", icon: "🎨", source: "Art History" },
    { fact: "A single cloud can weigh more than a million pounds.", icon: "☁️", source: "Meteorology" },
    { fact: "There is a fruit that tastes like chocolate pudding.", icon: "🍮", source: "Exotic Fruits" },
    { fact: "The world's largest grand piano was built by a 15‑year‑old.", icon: "🎹", source: "Music Facts" },
    { fact: "Octopuses can open jars from the inside.", icon: "🐙", source: "Animal Intelligence" },
    { fact: "The longest wedding veil was longer than 63 football fields.", icon: "👰", source: "Guinness Records" },
    { fact: "A group of rhinos is called a crash.", icon: "🦏", source: "Animal Groups" }
];

const quotes = [
    { text: "The beautiful thing about learning is nobody can take it away from you.", author: "B.B. King" },
    { text: "Education is the passport to the future.", author: "Malcolm X" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
    { text: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
    { text: "It is not that I'm so smart. But I stay with the questions much longer.", author: "Albert Einstein" },
    { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
    { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { text: "Learning is not attained by chance; it must be sought for with ardour and attended to with diligence.", author: "Abigail Adams" },
    { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
    { text: "Knowledge will bring you the opportunity to make a difference.", author: "Claire Fagin" },
    { text: "The beautiful thing about learning is that nobody can take it away from you.", author: "B.B. King" },
    { text: "Develop a passion for learning. If you do, you will never cease to grow.", author: "Anthony J. D'Angelo" },
    { text: "Education is not the filling of a pail, but the lighting of a fire.", author: "W.B. Yeats" },
    { text: "You are always a student, never a master. You have to keep moving forward.", author: "Conrad Hall" },
    { text: "Anyone who stops learning is old, whether at twenty or eighty.", author: "Henry Ford" },
    { text: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
    { text: "The more I learn, the more I realize how much I don't know.", author: "Albert Einstein" },
    { text: "Curiosity is the wick in the candle of learning.", author: "William Arthur Ward" },
    { text: "The whole purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris" },
    { text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso" },
    { text: "Learning is not compulsory... neither is survival.", author: "W. Edwards Deming" },
    { text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy" },
    { text: "A good education is a foundation for a better future.", author: "Elizabeth Warren" },
    { text: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
    { text: "The aim of education is the knowledge, not of facts, but of values.", author: "William S. Burroughs" },
    { text: "It's what you learn after you know it all that counts.", author: "John Wooden" },
    { text: "The only thing that interferes with my learning is my education.", author: "Albert Einstein" },
    { text: "Education is the key to unlock the golden door of freedom.", author: "George Washington Carver" },
    { text: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
    { text: "Education is the ability to listen to almost anything without losing your temper or your self‑confidence.", author: "Robert Frost" },
    { text: "Learning is not a spectator sport.", author: "D. Blocher" },
    { text: "I never teach my pupils, I only attempt to provide the conditions in which they can learn.", author: "Albert Einstein" },
    { text: "The beautiful thing about learning is nobody can take it away from you.", author: "B.B. King" }
];

const associations = [
    // original 10
    { prompt: "CAT", options: ["PET", "DOG", "CAR", "BOOK"], accepted: ["PET"] },
    { prompt: "DOG", options: ["PET", "BONE", "MEOW", "TREE"], accepted: ["PET","BONE"] },
    { prompt: "LOVE", options: ["HEART", "HATE", "MONEY", "WAR"], accepted: ["HEART"] },
    { prompt: "INDIA", options: ["COUNTRY", "CITY", "OCEAN", "MOUNTAIN"], accepted: ["COUNTRY"] },
    { prompt: "SUN", options: ["STAR", "PLANET", "MOON", "CLOUD"], accepted: ["STAR"] },
    { prompt: "MOON", options: ["SATELLITE", "STAR", "TIDE", "NIGHT"], accepted: ["SATELLITE","NIGHT"] },
    { prompt: "WATER", options: ["DRINK", "FIRE", "EARTH", "AIR"], accepted: ["DRINK"] },
    { prompt: "BOOK", options: ["READ", "EAT", "THROW", "BUY"], accepted: ["READ"] },
    { prompt: "MUSIC", options: ["SONG", "NOISE", "SILENCE", "DANCE"], accepted: ["SONG","DANCE"] },
    { prompt: "HAPPY", options: ["JOY", "SAD", "ANGRY", "FEAR"], accepted: ["JOY"] },
    // new 30 (total 40)
    { prompt: "SCHOOL", options: ["LEARN", "PLAY", "WORK", "SLEEP"], accepted: ["LEARN"] },
    { prompt: "TEACHER", options: ["GUIDE", "STUDENT", "PRINCIPAL", "PARENT"], accepted: ["GUIDE"] },
    { prompt: "FRIEND", options: ["BUDDY", "ENEMY", "STRANGER", "COLLEAGUE"], accepted: ["BUDDY"] },
    { prompt: "FAMILY", options: ["LOVE", "HOME", "OFFICE", "SCHOOL"], accepted: ["LOVE","HOME"] },
    { prompt: "FOOD", options: ["EAT", "DRINK", "THROW", "BURN"], accepted: ["EAT"] },
    { prompt: "SLEEP", options: ["DREAM", "AWAKE", "WORK", "EAT"], accepted: ["DREAM"] },
    { prompt: "MONEY", options: ["RICH", "POOR", "COIN", "BANK"], accepted: ["RICH","BANK"] },
    { prompt: "TIME", options: ["CLOCK", "WATCH", "MINUTE", "HOUR"], accepted: ["CLOCK","WATCH"] },
    { prompt: "NATURE", options: ["GREEN", "TREE", "BIRD", "FLOWER"], accepted: ["GREEN","TREE"] },
    { prompt: "ANIMAL", options: ["PET", "WILD", "ZOO", "FOREST"], accepted: ["PET","WILD"] },
    { prompt: "BABY", options: ["CUTE", "CRY", "CHILD", "MILK"], accepted: ["CUTE","CHILD"] },
    { prompt: "GAME", options: ["PLAY", "WIN", "LOSE", "SPORT"], accepted: ["PLAY","SPORT"] },
    { prompt: "STUDY", options: ["READ", "WRITE", "EXAM", "BOOK"], accepted: ["READ","BOOK"] },
    { prompt: "HOLIDAY", options: ["VACATION", "WORK", "SCHOOL", "REST"], accepted: ["VACATION","REST"] },
    { prompt: "BIRTHDAY", options: ["CAKE", "PARTY", "GIFT", "SURPRISE"], accepted: ["CAKE","PARTY","GIFT"] },
    { prompt: "WEATHER", options: ["RAIN", "SUN", "SNOW", "WIND"], accepted: ["RAIN","SUN"] },
    { prompt: "COLOUR", options: ["RED", "BLUE", "GREEN", "YELLOW"], accepted: ["RED","BLUE","GREEN","YELLOW"] },
    { prompt: "BICYCLE", options: ["RIDE", "WALK", "DRIVE", "FLY"], accepted: ["RIDE"] },
    { prompt: "OCEAN", options: ["SEA", "RIVER", "LAKE", "POND"], accepted: ["SEA"] },
    { prompt: "MOUNTAIN", options: ["HILL", "VALLEY", "PEAK", "CLIMB"], accepted: ["HILL","PEAK"] },
    { prompt: "DREAM", options: ["SLEEP", "WISH", "NIGHTMARE", "IMAGINE"], accepted: ["SLEEP","WISH"] },
    { prompt: "FESTIVAL", options: ["CELEBRATE", "MOURN", "WORK", "TRAVEL"], accepted: ["CELEBRATE"] },
    { prompt: "LIGHT", options: ["BRIGHT", "DARK", "BULB", "SUN"], accepted: ["BRIGHT","SUN"] },
    { prompt: "SOUND", options: ["MUSIC", "NOISE", "SILENCE", "ECHO"], accepted: ["MUSIC","NOISE"] },
    { prompt: "WINTER", options: ["COLD", "HOT", "SNOW", "ICE"], accepted: ["COLD","SNOW"] },
    { prompt: "SUMMER", options: ["HOT", "COLD", "SUN", "BEACH"], accepted: ["HOT","SUN"] },
    { prompt: "GOD", options: ["PRAY", "FAITH", "RELIGION", "BELIEVE"], accepted: ["PRAY","FAITH","BELIEVE"] },
    { prompt: "INDIA", options: ["BHARAT", "COUNTRY", "HINDUSTAN", "DELHI"], accepted: ["BHARAT","COUNTRY"] },
    { prompt: "LOVE", options: ["HEART", "KISS", "CARE", "AFFECTION"], accepted: ["HEART","CARE"] },
    { prompt: "CAT", options: ["MEOW", "KITTEN", "FELINE", "WHISKERS"], accepted: ["MEOW","KITTEN"] }
];

const guessWords = [
    // original 8
    { definition: "A four‑legged animal that says 'meow'.", options: ["Cat", "Dog", "Bird", "Fish"], correct: 0 },
    { definition: "A loyal animal that barks.", options: ["Dog", "Cat", "Rabbit", "Hamster"], correct: 0 },
    { definition: "A feeling of strong affection toward someone.", options: ["Love", "Anger", "Fear", "Sadness"], correct: 0 },
    { definition: "The supreme being in many religions.", options: ["God", "Human", "Angel", "Ghost"], correct: 0 },
    { definition: "The country known for the Taj Mahal.", options: ["India", "China", "USA", "Brazil"], correct: 0 },
    { definition: "A small furry pet that purrs.", options: ["Cat", "Turtle", "Parrot", "Snake"], correct: 0 },
    { definition: "Man's best friend.", options: ["Dog", "Cat", "Fish", "Bird"], correct: 0 },
    { definition: "A figure of speech using 'like' or 'as'.", options: ["Simile", "Metaphor", "Alliteration", "Hyperbole"], correct: 0 },
    // new 24 (total 32)
    { definition: "The planet we live on.", options: ["Earth", "Mars", "Jupiter", "Sun"], correct: 0 },
    { definition: "A place where students learn.", options: ["School", "Hospital", "Mall", "Park"], correct: 0 },
    { definition: "The colour of the sky on a clear day.", options: ["Blue", "Red", "Green", "Yellow"], correct: 0 },
    { definition: "A person who writes books.", options: ["Author", "Chef", "Pilot", "Doctor"], correct: 0 },
    { definition: "The sweet liquid made by bees.", options: ["Honey", "Milk", "Juice", "Tea"], correct: 0 },
    { definition: "A building where people live.", options: ["House", "Office", "School", "Mall"], correct: 0 },
    { definition: "The largest ocean on Earth.", options: ["Pacific", "Atlantic", "Indian", "Arctic"], correct: 0 },
    { definition: "A device used to make calls.", options: ["Phone", "Radio", "TV", "Microwave"], correct: 0 },
    { definition: "The coldest season of the year.", options: ["Winter", "Summer", "Spring", "Autumn"], correct: 0 },
    { definition: "A vehicle with two wheels.", options: ["Bicycle", "Car", "Bus", "Train"], correct: 0 },
    { definition: "The language most spoken in India.", options: ["Hindi", "English", "Tamil", "Bengali"], correct: 0 },
    { definition: "A tool used for writing.", options: ["Pen", "Spoon", "Fork", "Knife"], correct: 0 },
    { definition: "A large body of salt water.", options: ["Ocean", "River", "Lake", "Pond"], correct: 0 },
    { definition: "The planet closest to the sun.", options: ["Mercury", "Venus", "Earth", "Mars"], correct: 0 },
    { definition: "A fruit that is red and often associated with love.", options: ["Apple", "Banana", "Orange", "Grape"], correct: 0 },
    { definition: "A young dog.", options: ["Puppy", "Kitten", "Calf", "Cub"], correct: 0 },
    { definition: "The opposite of day.", options: ["Night", "Morning", "Evening", "Noon"], correct: 0 },
    { definition: "A popular Indian festival of lights.", options: ["Diwali", "Holi", "Eid", "Christmas"], correct: 0 },
    { definition: "A synonym for 'happy'.", options: ["Joyful", "Sad", "Angry", "Tired"], correct: 0 },
    { definition: "A large animal with a trunk.", options: ["Elephant", "Tiger", "Lion", "Bear"], correct: 0 },
    { definition: "The national currency of India.", options: ["Rupee", "Dollar", "Euro", "Yen"], correct: 0 },
    { definition: "The organ that pumps blood.", options: ["Heart", "Lungs", "Brain", "Liver"], correct: 0 },
    { definition: "A piece of furniture to sit on.", options: ["Chair", "Table", "Bed", "Shelf"], correct: 0 },
    { definition: "The act of telling a false statement.", options: ["Lie", "Truth", "Joke", "Riddle"], correct: 0 }
];

const highlights = [
    "📖 A new chapter awaits – keep reading!",
    "🐱 Cats rule the internet for a reason.",
    "❤️ Kindness is a language everyone understands.",
    "🇮🇳 India's diversity is its greatest strength.",
    "🕉️ Inner peace is the ultimate wealth.",
    "🎓 Every master was once a beginner.",
    "🐶 Paws and reflect – life is good.",
    "📚 A book is a dream you hold in your hands.",
    "🌍 The world is full of stories waiting to be heard.",
    "🍀 A little luck and lots of hard work go a long way.",
    "✨ Believe in yourself – you're doing great!",
    "🔥 One small positive thought can change your whole day.",
    "🌸 Bloom where you are planted.",
    "⭐ Shoot for the stars – even if you miss, you'll land among them.",
    "😊 Smile – it's the prettiest thing you can wear.",
    "🌞 Today is a perfect day to learn something new.",
    "🐘 Even elephants started as small calves.",
    "🍯 Sweet words are like honey to the soul.",
    "🎵 Music is the universal language of mankind.",
    "👫 Friends make the world brighter.",
    "🎨 Every expert was once a beginner.",
    "📝 Write your own story, one page at a time.",
    "🌧️ No rain, no flowers.",
    "🌙 The darkest hour has only sixty minutes.",
    "💪 You are stronger than you think.",
    "💡 An idea can change your world.",
    "🕊️ Peace begins with a smile.",
    "🍕 Pizza is always a good idea.",
    "🎉 Celebrate small victories.",
    "🌻 Keep your face always toward the sunshine.",
    "🍂 Autumn teaches us the beauty of letting go.",
    "🌟 Be the reason someone smiles today.",
    "💖 Love makes the world go round.",
    "🐢 Slow progress is still progress.",
    "🎂 Every day is a gift.",
    "⚡ A little spark can ignite a great fire.",
    "🍃 Breathe in calm, breathe out stress.",
    "🌺 Kindness is like a boomerang – it always returns.",
    "💎 You are a gem – never forget that.",
    "🏵️ The best view comes after the hardest climb.",
    "🍫 Chocolate solves everything. Almost.",
    "🐝 Busy as a bee, but sweet as honey.",
    "🌊 Life is like the ocean – it goes up and down.",
    "🚴 Every mile is a memory.",
    "🎯 Focus on progress, not perfection.",
    "💭 A dream written down becomes a goal.",
    "🎈 Let your dreams lift you higher.",
    "🧘 A calm mind is a powerful mind.",
    "📡 Stay tuned for more amazing discoveries.",
    "🦄 Magic is believing in yourself.",
    "🍀 Lucky are those who never stop learning.",
    "🐧 Waddle through challenges with a smile.",
    "🌵 Stay sharp, stay curious.",
    "🥇 You are a winner in the marathon of life.",
    "🚀 To the moon and beyond – keep reaching.",
    "🛶 Row through the tough times – calm waters ahead.",
    "🔔 Every day brings a new opportunity.",
    "🍿 Enjoy the show – life is a movie.",
    "🎻 Harmony comes from different notes playing together.",
    "💌 Send out love and it will return to you."
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing content
    await Content.deleteMany({});
    console.log('Cleared old content');

    // Insert all types
    const allData = [
      ...curiosities.map(d => ({ type: 'curiosity', data: d })),
      ...facts.map(d => ({ type: 'fact', data: d })),
      ...quotes.map(d => ({ type: 'quote', data: d })),
      ...associations.map(d => ({ type: 'association', data: d })),
      ...guessWords.map(d => ({ type: 'guessWord', data: d })),
      ...highlights.map(d => ({ type: 'highlight', data: { text: d } }))
    ];

    await Content.insertMany(allData);
    console.log(`Seeded ${allData.length} items successfully.`);
    process.exit(0);
  } catch (err) {
    console.error('Seeding failed:', err);
    process.exit(1);
  }
}

seed();